### ISSUE TITLE
Add text for when map data is loading

### ISSUE THREAD

**Issue by jakecoppinger** [jakecoppinger/better-intersections#1]
Something as similar as `<p>Loading data...</p>` in the top left panel would do the job!

**Comment by Uzaif-Sheikh** [comment]
Hi Jake, I'm Uzaif, a software dev from UNSW. Ayaan and I came upon this project together. I'm also keen to contribute. I'm taking up this issue. Thanks

**Comment by jakecoppinger** [comment]
Awesome! Please let me know if you have any troubles getting started, very happy to help.

**Comment by jakecoppinger** [comment]
Fixed in https://github.com/jakecoppinger/better-intersections/pull/5
