### ISSUE TITLE
Add CSV export of Supabase Postgres

### ISSUE THREAD

**Issue by jakecoppinger** [jakecoppinger/better-intersections#18]
Will likely need to call `getIntersectionMeasurements()` and download to a `.csv`. Add copy text and link on about page.

**Comment by Uzaif-Sheikh** [comment]
Hi Jake, working on it.

**Comment by jakecoppinger** [comment]
Completed in #30

**Comment by jakecoppinger** [comment]
FYI I shared this update (and credited your PR) at https://mastodon.jakecoppinger.com/@jake/111164976296218470
