### ISSUE TITLE
Format timestamps in local time rather than UTC

### ISSUE THREAD

**Issue by jakecoppinger** [jakecoppinger/better-intersections#37]
Timestamps are stored as UTC ISO8601 timestamps, and are currently displayed as such.

With a couple of lines we should be able to import a date formatting library and display as a more "friendly" time in the popup on the frontend.

Ideally this would use the location coordinates to find the local timezone, otherwise displaying in Sydney time should be fine.

Ideally it would look up the Sydney timezone (AEST vs ADST) at the time of capture, but displaying in the current Sydney time would be better than UTC. As long as we include UTC+11 (or whatever the offset is) the user is able to convert if it's incorrect.

**Comment by 17Ayaan28** [comment]
I'll pick this up.

**Comment by jakecoppinger** [comment]
Completed in https://github.com/jakecoppinger/better-intersections/pull/39
