### ISSUE TITLE
No intersection Pins showing

### ISSUE THREAD

**Issue by Johnd1988** [jakecoppinger/better-intersections#38]
No intersection Pins are showing. Checked by looking in Sydney CBD. Additionally checked across two seperate Android devices.

**Comment by 17Ayaan28** [comment]
![Screenshot 2023-12-20 at 12 09 55 am](https://github.com/jakecoppinger/better-intersections/assets/61399823/be9b1a5a-9b76-4e5b-8752-67e91c0460a7)

Hey John, I am able to see interesections on my laptop and iphone. Maybe the data was taking time to load ?
