### ISSUE TITLE
Large (~10mb) JS bundle size

### ISSUE THREAD

**Issue by jakecoppinger** [jakecoppinger/better-intersections#8]
Cloudflare reports around an 8mb bundle size. I haven't looked into the cause of this - we might be able to achieve some easy wins by adjusting some build config settings or library imports.

If it's not a simple fix I don't think we should stress too much - time to map pin load is more dependant on the OSM node requests.

**Comment by 17Ayaan28** [comment]
I will try looking into this. @jakecoppinger would you be able to recommend some resources to learn to reduce this ?

**Comment by 17Ayaan28** [comment]
Hey @jakecoppinger, sorry for the slight absence - been watching the cricket world cup. I will create another PR looking into imports based on your recommendations.
